#!/usr/bin/env bash

nixos-generate-config --dir ~/nix

sleep 2 && git add .

for arg in "$@"; do
  case $arg in
  --disko)
    sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode destroy,format,mount ./disko.nix
    ;;
  --install)
    sudo nixos-install --flake .#Orion
    ;;
  --del)
    sudo rm -rf /mnt/root/.nix-defexpr/channels
    sudo rm -rf /mnt/nix/var/nix/profiles/per-user/root/channels
    ;;
  esac
done
